### ISSUE TITLE
Integrate Frontend Form Submission and API Fetch Logic for Chat Posts

### ISSUE THREAD

**Issue by AlexRubio1** [alexgstf/studybuddy_frontend#9]
#### Description/ Objectives
We need to integrate the backend API logic for handling post submissions and rendering posts into the existing frontend of our chat application. The primary goal is to allow users to submit posts via a form and dynamically fetch and display posts in the UI. This includes proper error handling and API communication.

---

#### Task Breakdown

1. **HTML Structure:**
   - Ensure the following HTML structure exists:
     ```html
     <div class="main">
         <div class="content">
             <div class="form-container">
                 <form id="channelForm">
                     <div class="form-inputs">
                         <input type="text" id="title" name="title" placeholder="Enter Title Here" required>
                     </div>
                     <textarea id="textArea" name="textArea" placeholder="Post Here" required></textarea>
                     <button type="submit">Post</button>
                 </form>
             </div>
             <div id="culinaryposts"></div>
         </div>
     </div>
     ```

2. **API Configuration:**
   - Use `pythonURI` and `fetchOptions` for backend API configuration. Example:
     ```javascript
     export const pythonURI = 'http://your-api-endpoint.com';  // Replace with actual API endpoint
     export const fetchOptions = {
         method: 'GET',
         headers: {
             'Content-Type': 'application/json',
             // Include other headers like authentication tokens if required
         }
     };
     ```

3. **JavaScript Integration:**
   - Implement logic for:
     - Fetching posts from the backend API on page load.
     - Handling form submission:
       - Send the input data to the API.
       - Refresh the list of posts upon successful submission.
     - Displaying fetched posts dynamically in the `#culinaryposts` container.

     Example code for submission and fetching/ Also example from last post chat:
     ```javascript
     import { pythonURI, fetchOptions } from './assets/js/api/config.js';

     async function fetchChannels() {
         try {
             const groupName = 'Culinary Posts';
             const responseData = { group_name: groupName };

             const response = await fetch(`${pythonURI}/api/channels/filter`, {
                 ...fetchOptions,
                 method: 'POST',
                 headers: { 'Content-Type': 'application/json' },
                 body: JSON.stringify(responseData)
             });

             if (!response.ok) {
                 throw new Error('Failed to fetch channels: ' + response.statusText);
             }

             const channels = await response.json();
             const container = document.getElementById("culinaryposts");
             container.innerHTML = "";

             channels.forEach(channel => {
                 const card = document.createElement("div");
                 card.classList.add("card");

                 const title = document.createElement("h3");
                 title.classList.add("card-title");
                 title.textContent = channel.name;

                 const description = document.createElement("p");
                 description.classList.add("card-description");
                 description.textContent = channel.attributes["content"];

                 card.appendChild(title);
                 card.appendChild(description);
                 container.appendChild(card);
             });
         } catch (error) {
             console.error('Error fetching channels:', error);
         }
     }

     document.getElementById('channelForm').addEventListener('submit', async function(event) {
         event.preventDefault();
         const title = document.getElementById('title').value;
         const content = document.getElementById('textArea').value;
         const group_id = 13;

         const channelData = { name: title, group_id, attributes: { content } };

         try {
             const response = await fetch(`${pythonURI}/api/channel`, {
                 ...fetchOptions,
                 method: 'POST',
                 headers: { 'Content-Type': 'application/json' },
                 body: JSON.stringify(channelData)
             });

             if (!response.ok) {
                 throw new Error('Failed to add channel: ' + response.statusText);
             }

             fetchChannels();
             document.getElementById('channelForm').reset();
         } catch (error) {
             console.error('Error adding channel:', error);
             alert('Error adding channel: ' + error.message);
         }
     });

     // Initial fetch to load posts
     fetchChannels();
     ```

4. **Styling (Optional):**
   - Add CSS for styling the dynamically rendered posts. Example:
     ```css
     .card {
         background: rgba(255, 255, 255, 0.1);
         border-radius: 10px;
         padding: 15px;
         margin-bottom: 15px;
         box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
     }

     .card-title {
         font-size: 1.5rem;
         margin-bottom: 0.5rem;
     }

     .card-description {
         font-size: 1rem;
         color: #fff;
     }
     ```

---

#### Acceptance Criteria
- [ ] Posts can be submitted via the form and displayed dynamically in the frontend.
- [x] Fetch requests correctly handle API responses and errors.
- [x] Form resets after successful submission.
- [x] Posts are styled consistently with the application design.
## NEW BURNDOWN

- [ ] **Fix API Integration**  
  - Ensure the `API_URL` endpoint is accurate for production.  
  - Add robust error handling for failed API requests.  

- [ ] **Authentication Flow**  
  - Validate the `getAuthToken` function to retrieve the correct JWT token.  
  - Add redirection for unauthorized users to a login page or display a proper error message.  

- [ ] **UI Adjustments**  
  - Ensure "Save Post" reflects user actions immediately in the UI.  
  - Verify the "Delete" button removes posts correctly without requiring a page reload.  

- [ ] **Responsive Design**  
  - Adapt layout for smaller screens (e.g., mobile-friendly).  
  - Ensure buttons like "New Post" and "Close" are usable across all screen sizes.  

- [ ] **Post Rendering**  
  - Fix issues with duplicate rendering of posts when refreshing data.  
  - Ensure uploaded images render properly within the post cards.  

- [ ] **Input Validation**  
  - Add validation to prevent empty `noteInput` submissions.  
  - Restrict image file types and limit upload size for better handling.  

---

# ✨ New Ideation List
**Future Features and Enhancements:**

- [x] **User Profiles**  
  - Display user avatars and usernames alongside posts.  
  - Add profile management to let users update their details.  

- [ ] **Rich Text Editor**  
  - Replace `textarea` with a rich text editor for better formatting options (e.g., bold, italics, lists).  
  - Allow embedding links and other rich media into posts.  

- [ ] **Tagging System**  
  - Introduce post tags for categorization (e.g., #Math, #Science).  
  - Add a filtering option based on tags.  

- [ ] **Like & Comment System**  
  - Enable users to like posts and add comments.  
  - Show a count of likes and comments for each post.  

- [ ] **Search and Filter**  
  - Add a search bar to filter posts by keyword.  
  - Implement filters by date, tags, or content type (text/image).  

- [ ] **Dark Mode**  
  - Include a toggle to switch between light and dark themes for accessibility.  

- [x] **Enhanced Moderation**  
  - Build a moderation dashboard for admins to manage flagged posts.  
  - Add indicators for posts under review or flagged for violations.  

- [ ] **Notifications**  
  - Notify users about new posts or comments on their posts.  
  - Show notification counts as badges in the UI.  

- [ ] **Offline Mode**  
  - Cache posts locally for offline viewing.  
  - Allow offline post drafts that sync when the user reconnects.  

- [ ] **Analytics Dashboard**  
  - Add a section for community stats (e.g., posts created, active users).  
  - Track popular topics and user engagement metrics.
